"""RPS bot configuration variables."""

PHYSICAL=True

CACHE_TIME=0.5

COUNT_FROM=3
DELAY=3
TOO_FAST_DELAY=1

ANGLE_CUTOFF_FREESTYLE=100
ANGLE_CUTOFF_GAME=100

VERBOSE=True
DISPLAY_DETECTION=True
DISPLAY_FPS=False
DISPLAY_ANGLES=False
DISPLAY_CLASS_LABELS=False

MODEL_COMPLEXITY=1

MIN_DETECTION_CONFIDENCE_FREESTYLE=0.2
MIN_TRACKING_CONFIDENCE_FREESTYLE=0.9
MIN_DETECTION_CONFIDENCE_GAME=0.1
MIN_TRACKING_CONFIDENCE_GAME=0.9

PAPER_COLOR_INTENSITY=1.5
SCISSOR_COLOR_INTENSITY=1
ROCK_COLOR_INTENSITY=1
